theme: jekyll-theme-cayman
title: Avocadoge (ä-və-ˈkä-(ˌ)dōj)
description: The latest and best Avocado/Doge hybrid token, available soon on BSC Network. Enjoy Avocadoge (ä-və-ˈkä-(ˌ)dōj) responsibly.

# social:
socials:
  twitter: https://twitter.com/unabris

twitter:
  username: lorepirri
