theme: jekyll-theme-cayman
title: Avocadoge (ä-və-ˈkä-(ˌ)dōj)
description: The latest and best Avocado/Doge hybrid token, available soon on BSC Network. Enjoy Avocadoge (ä-və-ˈkä-(ˌ)dōj) responsibly.
